# Generated by Django 2.2.2 on 2019-06-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
